export const ABOUT_LIST_TAB = {

    'The project': 'Every day, CLS generates thousands of high-resolution radar (SAR) images to study meteorological phenomena and ocean activities. While these images make it possible to highlight the presence of illegal fishing, accidental pollution of the oceans, or hazards such as cyclones, the detection and identification of these meteorological and oceanic phenomena is however long and tedious. CLS is therefore developing an Artificial Intelligence (AI) system capable of simulating virtual SAR images and recognizing the different meteorological phenomena present in these images. Like any phase in the development of a deep learning algorithm, AI must first learn from its mistakes and know whether the virtual images it creates are realistic or not. This learning phase usually involves the development of a turing test, a test to find out if an AI is capable of deceiving a human. The role of our team is therefore to develop this Turing Test and the web application to present the project in React. ',
    
    'The turing test': 'The Turing test, originally called the imitation game by Alan Turing in 1950, is a test of a machine\'s ability to exhibit intelligent behaviour equivalent to, or indistinguishable from, that of a human. Turing proposed that a human evaluator would judge natural language conversations between a human and a machine designed to generate human-like responses. The evaluator would be aware that one of the two partners in conversation is a machine, and all participants would be separated from one another. The conversation would be limited to a text-only channel such as a computer keyboard and screen so the result would not depend on the machine\'s ability to render words as speech. If the evaluator cannot reliably tell the machine from the human, the machine is said to have passed the test. The test results do not depend on the machine\'s ability to give correct answers to questions, only how closely its answers resemble those a human would give.',
    

    
    'CLS': 'CLS is an international company, a pioneer in providing Earth observation and monitoring solutions since 1986. Its vision is to imagine and deploy innovative solutions to understand and protect our Planet and manage its resources sustainably. CLS employs 750 people at its headquarters in Toulouse and at its 26 other sites around the world. The company operates in 6 strategic business areas: sustainable fisheries management, environmental monitoring, maritime safety, fleet management, energy & mining and space & ground systems. In particular, the company provides satellite services based on the location and collection of environmental data, the observation of oceans and continental waters, and the monitoring of land and maritime activities.',

   

}