# Generated by Django 3.1.2 on 2020-10-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
