# Generated by Django 3.1.2 on 2020-11-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201011_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
