# Generated by Django 3.1.3 on 2020-11-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201115_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageTest',
            new_name='UnitTest',
        ),
    ]
