# Generated by Django 3.1.4 on 2020-12-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201129_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesar',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='TypeImage',
        ),
    ]
