# Generated by Django 3.1.4 on 2020-12-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201205_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unittest',
            name='testTuring',
        ),
        migrations.AddField(
            model_name='unittest',
            name='user',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='core.testuser'),
            preserve_default=False,
        ),
    ]
