# Generated by Django 3.1.4 on 2020-12-07 10:28

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201207_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittest',
            name='testTuring',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.turingtest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagesar',
            name='image',
            field=models.ImageField(upload_to=core.models.recipe_image_file_path),
        ),
    ]
